version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=development
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
