version: '3.8'

services:
  mlflow-server:
    image: ghcr.io/mlflow/mlflow
    container_name: mlflow-server
    ports:
      - "5000:5000"
    volumes:
      - mlflow_volume:/mlflow
    command: sh -c "mlflow server --host 0.0.0.0"
volumes:
  mlflow_volume:
    name: mlflow_volume
    driver: local

