services:
  spark-master:
    image: bitnami/spark:3.4.2
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network
    volumes:
      - ./spark-data:/opt/spark/data
      - ./jars:/opt/spark/jars
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 5s
      timeout: 3s
      retries: 3

  spark-worker-1:
    image: bitnami/spark:3.4.2
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=6G
      - SPARK_WORKER_CORES=3
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8081:8081"
    networks:
      - spark-network
    volumes:
      - ./spark-data:/opt/spark/data
      - ./jars:/opt/spark/jars
    depends_on:
      - spark-master

  spark-worker-2:
    image: bitnami/spark:3.4.2
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=6G
      - SPARK_WORKER_CORES=3
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - "8082:8081"
    networks:
      - spark-network
    volumes:
      - ./spark-data:/opt/spark/data
      - ./jars:/opt/spark/jars
    depends_on:
      - spark-master

  postgres:
    image: postgres:14
    container_name: spark-postgres
    environment:
      - POSTGRES_USER=spark
      - POSTGRES_PASSWORD=sparkpass
      - POSTGRES_DB=sparkdb
    ports:
      - "5432:5432"
    networks:
      - spark-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - spark-network
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:v0.11.1
    container_name: postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://spark:sparkpass@postgres:5432/sparkdb?sslmode=disable"
    ports:
      - "9187:9187"
    networks:
      - spark-network
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - spark-network
    depends_on:
      - prometheus

networks:
  spark-network:
    driver: bridge

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:
