global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka-cluster-1'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.178.0.3:5556'] #gcp에서 테스트

  - job_name: 'kafka-cluster-2'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.178.0.7:5556'] #gcp에서 테스트

  - job_name: 'kafka-cluster-3'
    scrape_interval: 15s
    static_configs:
      - targets: ['10.178.0.9:5556'] #gcp에서 테스트

  - job_name: 'node-exporter'
    static_configs:
      - targets:
          - '34.64.82.106:9100'   # airflow
          - '34.64.115.243:9100'  # backend