global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kafka_exporter'
    static_configs:
      - targets: ['34.64.141.221:9308']

  #- job_name: 'node-exporter'
  #  static_configs:
  #    - targets:
  #        - '34.64.82.106:9100'   # airflow
  #        - '34.64.115.243:9100'  # backend