# Master Node docker-compose1.yaml

version: '3'
services:
  spark-master:
    image: bitnami/spark:3.4.2
    networks:
      - kafka_network
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    ports:
      - '8080:8080'
      - '7077:7077'
      - '4040:4040'
    volumes:
      - ./data:/opt/spark/data

  jmx-exporter:
    image: bitnami/jmx-exporter:0.20.0
    container_name: jmx-exporter-1
    environment:
      - JVM_OPTS=-javaagent:/opt/jmx-exporter/jmx_prometheus_javaagent.jar=5556:/opt/jmx-exporter/config.yaml
    ports:
      - "5556:5556"
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge
  

    


